### ISSUE TITLE
Training with simOTA

### ISSUE THREAD

**Issue by Fschoeller** [WongKinYiu/yolor#122]
Hi! 
How do I train with simOTA?
Thanks.

**Comment by Fschoeller** [comment]
@WongKinYiu 
I can see you state mAP for models trained with simOTA, e.g. YOLOR-CSP-X. Is this implemented in the repo?
Thank you for your time.

**Comment by WongKinYiu** [comment]
Hello, 
Because the main part of simOTA is re-implemented by our partner, we will release the corresponding code after he publish his work. Currently you could integrate simOTA from YOLOX github by yourself, just notice there are a little gap of positive sample assignment between YOLOR and YOLOX, it need a little bit modification.

**Comment by Fschoeller** [comment]
Alright, thanks a lot.

**Comment by X-WhyY** [comment]
hi，
If I want to integrate simOTA from YOLOX , do I need to change yolor to an anchor free detector? 
Thanks.

**Comment by Chilicy** [comment]
Hello,  @WongKinYiu 
I tried to integrate SimOTA and didn't get AP improvements as you plotted.
I wonder when the corresponding code will be released.
Thanks!
