### ISSUE TITLE
can you share yolov4-p7 and yolov4-p6 pretrained model

### ISSUE THREAD

**Issue by wanganding** [WongKinYiu/yolor#56]

**Comment by WongKinYiu** [comment]
https://github.com/WongKinYiu/ScaledYOLOv4

**Comment by happyjohn360** [comment]
@WongKinYiu 
Hi, I try to download yolov4-p6 pretrained from ScaledYOLOv4 repo,
but I got an error
`   ModuleNotFoundError: No module named 'models.yolo' `
 ` During handling of the above exception, another exception occurred:`

` RuntimeError: shape '[512, 512, 1, 1]' is invalid for input of size 64135`

I think the reason is the pretrained model we downloaded is trained from yaml
can you please provide a cfg version(darknet) yolov4-p5、p6、p7 pretrained weight like the yolor_p6.pt?


Thank you！！！
